Überarbeitung Stand der Technik
DHBW-FN-TIT20/sa-hs-lb-jb pull request #66
Opened 2023-06-20 20:06 UTC by johannesbrandenburger

2023-06-22 18:47 UTC, schuler-henry requested changes
Formal:
- Im präsens schreiben, nicht Vergangenheit
- Abkürzungen nutzen für Begriffe die oft verwendet werden (**\ac**)
- Wird ein Begriff nur einmalig / selten verwendet -> immer Langform

Inhaltlich:
- Ich denke eine Tabellarische Übersicht in der Reihenfolge des Textes wäre besser für eine Übersicht.
- Außerdem: Vielleicht nochmal etwas umsortieren, dass es etwas geordneter ist. 
  - Aktuell kommt MFCC/LPC -> LPC -> LPCC -> MFCC -> MFCC/LPC
  - Vorschlag: LPC -> LPCC -> MFCC -> MFCC/LPC -> MFCC/LPC
- Wenn es Zahlen zu den Features aus den Arbeiten gibt (was es ziemlich sicher gibt) sollten die dazu!
  - Bsp.: Mit MFCC konnten Sprecher zu xy% korrekt zugeordnet werden
  - Dadurch bekommt man als Leser ein Gefühl dafür was du mit "gut" oder "sehr gut" meinst. Allgemein sind Begriffe wie "gut" ja subjektive/wertende begriffe und dadurch eher weniger wissenschaftlich.

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
> +Dieses Kapitel zeigt, wie verschiedene vorrangeganene Projekte Features erhoben haben, welche Merkmale davon als effektiv erachtet wurden und welche Klassifikations-Modelle genutzt werden können.
`Dieses Kapitel zeigt, welche Merkmale von verschiedene vorangehende Arbeiten verwendet werden und wie effektiv diese im direkten Vergleich sind.
Dabei wird ebenfalls auf die verwendeten Klassifikations-Modell eingegangen.`

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
> +Qi (Peter) Li, ein Elektrotechnik-Doktor und Experte für Sprecherauthentifizierung, untersuchte in seinem Buch \gqq{Speaker Authentification}, relevante Merkmale für die Sprechererkennung \autocite{l
Allgemein würde ich im Präsens schreiben.
-> `untersucht in seinem Buch`

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
> +MFCC und LPC sind sehr gute Merkmale zur Identifizierung eines Sprechers in ruhigen Umgebungen, aber ihre Leistung nimmt in Umgebungen mit Hintergrundrauschen ab \autocite[vgl.][S. 136]{li_speaker_20
MFCC und LPC als \ac Command

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
>  Die ersten und zweiten Ableitungen von MFCC werden oft auch noch genutzt, tragen laut QI (Peter) Li allerdings nicht zu einer Verbesserung des Authentifizierungssystems bei \autocite[vgl.][S. 143]{li
`Meist werden die Koeffizienten der ersten und zweiten Ableitung von \ac{MFCC} zusätzlich genutzt, diese tragen laut ...`
Kleines "i" bei `Qi`

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
> +Neben den Hauptmerkmalen MFCC und LPC wurden in dem Buch auch Gammatone-Merkmale bewertet, die das menschliche Hören modellieren sollen.
`... \ac{LPC} werden zusätzlich Gammatone-Merkmale bewertet, die ...`

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
>  Diese können auch relevante Daten für eine Sprecherauthentifizierung liefer \autocite[vgl.][S. 111, 117]{li_speaker_2012}.
`Diese können ebenfalls ... liefern` ("n" fehlt)

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
> +Qi (Peter) Li hat im Zuge seiner Arbeit auch ein ganz neues Merkmal (CFCC) entwickelt, das ebenfalls das menschliche Gehör nachahmen soll und in seinen Untersuchungen am besten abgeschnitten hat \aut
` ein neues Merkmal (CFCC) ...`
-> Kommt CFCC nie wieder vor -> nur Langform, sonst Langform + Abkürzung

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
> +Aber auch LPCC, PLP und FM werden als effektive Merkmale genannt und können zusammen mit MFCC sehr gute Ergebnisse erzielen \autocite[vgl.][S. 6, 67]{li_advanced_nodate}.
`Zusätzlich werden \ac{LPCC}, ... als effektive ..., welche zusammen mit \ac{MFCC} sehr gute Ergebnisse erzielen können.`
-> Auch hier: Wird PLP/FM öfters verwendet -> \ac{}. sonst nur Langform (ohne die Langform könnte die Abkürzung alles bedeuten)

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
>  Auch eine ältere Untersuchung von Reynolds and Rose ergab, dass LPC in einer ruhigen Umgebung effektiv ist, MFCC allerdings robuster ist und daher von den Autoren bevorzugt wurde \autocite[vgl.][S. 2
Was bedeutet "ältere Untersuchung"? Warum älter?
Eventuell besser: "vorangehende Untersuchung"

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
> +Als Klassifikations-Model wurden hierbei Gaussian Mixture Models (GMM) genutzt und als effektiv erachtet.
Auch für GMM: kommt öfter vor -> ac, sonst nur langform

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
> +Allerdings werden auch neuronale Netze, als ein neueres Modell, aufgeführt und auch Hidden Markov Models, welche eigentlich für Spracherkennung genutzt werden, werden als Möglichkeit erwähnt \autocit
warum "als ein neueres Modell"? Ist das inhaltlich relevant?
Was heist "aufgeführt"? Nur genannt oder auch getestet?
Insgesamt ist der Satz finde ich auch zu verschachtelt/komplex -> evtl. aufteilen in zwei Sätze.

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
> +Ein anderes Paper, bei dem die benötigte Rechenleistung für die Merkmalsberechnung kritisch war, nannte LPCC als bestes Merkmal \autocite[vgl.][S. 7]{thullier_text-independent_2017}.
Meinst du `Ein weiters Paper, welches sich mit Sprecherauthentifikation auf Performance-kritischen Systemen beschäftigt, nennt \ac{LPCC} als bestes Merkmal.`?

So wie es aktuell ist, kommt die Aussage die du machen willst (Der Fokus liegt in dem Paper vorallem darauf, dass die Features auch performant/mit wenig rechenleistung berechnet werden können) finde ich nicht wirklich rüber.

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
>  Allerdings vergleichen sie auch verschiedene Kombinationen von MFCC, dMFCC, ddMFCC, DWT und LPC.
`dMFCC` muss erklärt werden (dass das "d" für delta und damit die Ableitung steht) -> Entweder oben wenn von erster und zweiter Ableitund die Rede ist die Abkürzung einführen oder hier.

2023-06-22 18:47 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
> +Durch das Hinzufügen von ZCR konnten diese sogar noch verbessert werden.
Was ist ZCR?
"sogar" ist auch eher umgangsprachlich würde ich sagen. -> weglassen

2023-07-03 11:27 UTC, johannesbrandenburger commented on latex/chapter/Stand_der_Technik.tex
>  Auch eine ältere Untersuchung von Reynolds and Rose ergab, dass LPC in einer ruhigen Umgebung effektiv ist, MFCC allerdings robuster ist und daher von den Autoren bevorzugt wurde \autocite[vgl.][S. 2
die ist halt einfach schon etwas älter als die anderen Bücher?

2023-07-03 11:29 UTC, johannesbrandenburger commented on latex/chapter/Stand_der_Technik.tex
> +Als Klassifikations-Model wurden hierbei Gaussian Mixture Models (GMM) genutzt und als effektiv erachtet.
Wieso? Wenn der Leser es noch wo anderes ließt kennt er schonmal die abkürzung

2023-07-04 07:34 UTC, schuler-henry commented on latex/chapter/Stand_der_Technik.tex
> +Als Klassifikations-Model wurden hierbei Gaussian Mixture Models (GMM) genutzt und als effektiv erachtet.
Ja, aber dann gehört es trotzdem zu den Abkürzungen

2023-07-05 07:19 UTC, johannesbrandenburger commented on latex/chapter/Stand_der_Technik.tex
> +Als Klassifikations-Model wurden hierbei Gaussian Mixture Models (GMM) genutzt und als effektiv erachtet.
Hä? Dann wird ja nur die Langform geschrieben?

2023-07-06 19:48 UTC, merged