Festlegung der Systemanforderungen
DHBW-FN-TIT20/sa-hs-lb-jb pull request #67
Opened 2023-06-21 07:43 UTC by johannesbrandenburger

2023-06-22 17:26 UTC, schuler-henry requested changes
Hab die Verbesserungen kommentiert.

2023-06-22 17:26 UTC, schuler-henry commented on latex/chapter/Konzeption.tex
> +    \item Das System soll lediglich ein Demo-System darstellen, welches die Machbarkeit eines test-unabhängigen Sprecheridentifikationssystems aufzeigt. Es soll nicht in einem produktiven Umfeld eing
Was ist ein `test-unabhängiges Sprecheridentifikationssystem`?

2023-06-22 17:26 UTC, schuler-henry commented on latex/chapter/Konzeption.tex
> +    \item Der Datensatz für das System ist zu Begin festgelegt. Das heißt, es werden nur bereits bekannte Sprecher identifiziert. Zudem können keine neuen Sprecher regisiert werden, es ist also auch
`registriert` (typo)
`registriert werden, wodurch das Sprecheridentifikationssystem keine dynamische Erweiterung um Sprecher bereitstellen muss.`

2023-06-22 17:26 UTC, schuler-henry commented on latex/chapter/Konzeption.tex
> +    \item Ein Sprecher wird authentifiziert, wenn ein Audio-Clip von 20 Sekunden des Sprechers in das System gegeben wird. Der Audio-Clip ist dem System bisher unbekannt, aber in ähnlichen Bedingunge
`Zur Authentifizierung eines Sprechers wird ein 20 sekündiger Audio-Clip an das System übermittelt.`

Wichtig: 
Wenn wir von `ähnlichen Bedingungen` sprechen, müssen wir später an einem Punkt genauer beschreiben/definieren was wir mit "ähnlich" meinen.

2023-06-22 17:26 UTC, schuler-henry commented on latex/chapter/Konzeption.tex
> +    \item Das Sprecheridentifikationssystems sollte im Back-End laufen. Die Bedienung erfolgt über eine Webapplikation, die mit dem System über eine Schnittstelle kommuniziert.
`Das Sprecheridentifikationssystem ist Teil des Back-Ends.`

2023-06-22 17:26 UTC, schuler-henry commented on latex/chapter/Konzeption.tex
> +    \item So soll der Nutzer des Demo-Systems testen können, was passiert, wenn ein zum authentifizierenden Sprecher passender bzw. unpassender Verifikations-Clip ins System gegeben wird.
`... was passiert, wenn ein zu dem zu authentifizierenden Sprecher ... -Clip an das System übermittelt wird.`

2023-06-22 17:26 UTC, schuler-henry commented on latex/chapter/Konzeption.tex
> +    \item Das System soll dem Nutzer dann Informationen über die Identifikations-Verteilung (zu welchem Sprecher passt der Clip zu welchem Prozentsatz) und dem Authentifizierungs-Status (\gqq{erfolgr
`... und den Authentifizierungs- ...`

2023-06-22 17:42 UTC, johannesbrandenburger commented on latex/chapter/Konzeption.tex
> +    \item Ein Sprecher wird authentifiziert, wenn ein Audio-Clip von 20 Sekunden des Sprechers in das System gegeben wird. Der Audio-Clip ist dem System bisher unbekannt, aber in ähnlichen Bedingunge
Dann sagen wir halt gleich 😂 das stimmt ja

2023-07-02 16:08 UTC, schuler-henry requested changes

2023-07-02 16:08 UTC, schuler-henry commented on latex/chapter/Konzeption.tex
> +    \item Das Sprecheridentifikationssystems sollte Teil des Back-Ends sein. Die Bedienung erfolgt über eine Webapplikation, die mit dem System über eine Schnittstelle kommuniziert.
```suggestion
    \item Das Sprecheridentifikationssystem sollte Teil des Back-Ends sein. Die Bedienung erfolgt über eine Webapplikation, die mit dem System über eine Schnittstelle kommuniziert.
```

2023-07-03 09:28 UTC, schuler-henry approved these changes

2023-07-03 09:29 UTC, merged